name: LlamaYells
version: 1.0
description: The llamas yell out their location when you ride them
author: leee leee
website: denmc.online

main: org.LlamaYells.Main

permissions:
    leeeleees.llamas:
